import type { AppLocation } from '@/features/location/types/location.types';

export const TAMIL_NADU_LOCATIONS: AppLocation[] = [
  {
    id: 'chennai',
    name: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 13.0827,
    longitude: 80.2707,
    source: 'manual',
  },
  {
    id: 'coimbatore',
    name: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 11.0168,
    longitude: 76.9558,
    source: 'manual',
  },
  {
    id: 'madurai',
    name: 'Madurai',
    district: 'Madurai',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 9.9252,
    longitude: 78.1198,
    source: 'manual',
  },
  {
    id: 'tiruchirappalli',
    name: 'Tiruchirappalli',
    district: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.7905,
    longitude: 78.7047,
    source: 'manual',
  },
  {
    id: 'salem',
    name: 'Salem',
    district: 'Salem',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 11.6643,
    longitude: 78.146,
    source: 'manual',
  },
  {
    id: 'tirunelveli',
    name: 'Tirunelveli',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 8.7139,
    longitude: 77.7567,
    source: 'manual',
  },
  {
    id: 'tenkasi',
    name: 'Tenkasi',
    district: 'Tenkasi',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 8.959,
    longitude: 77.3152,
    source: 'manual',
  },
  {
    id: 'thoothukudi',
    name: 'Thoothukudi',
    district: 'Thoothukudi',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 8.7642,
    longitude: 78.1348,
    source: 'manual',
  },
  {
    id: 'vellore',
    name: 'Vellore',
    district: 'Vellore',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 12.9165,
    longitude: 79.1325,
    source: 'manual',
  },
  {
    id: 'erode',
    name: 'Erode',
    district: 'Erode',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 11.341,
    longitude: 77.7172,
    source: 'manual',
  },
  {
    id: 'tiruppur',
    name: 'Tiruppur',
    district: 'Tiruppur',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 11.1085,
    longitude: 77.3411,
    source: 'manual',
  },
  {
    id: 'thanjavur',
    name: 'Thanjavur',
    district: 'Thanjavur',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.787,
    longitude: 79.1378,
    source: 'manual',
  },
  {
    id: 'dindigul',
    name: 'Dindigul',
    district: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3673,
    longitude: 77.9803,
    source: 'manual',
  },
  {
    id: 'karur',
    name: 'Karur',
    district: 'Karur',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.9601,
    longitude: 78.0766,
    source: 'manual',
  },
  {
    id: 'namakkal',
    name: 'Namakkal',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 11.2189,
    longitude: 78.1674,
    source: 'manual',
  },
  {
    id: 'kanchipuram',
    name: 'Kanchipuram',
    district: 'Kanchipuram',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 12.8342,
    longitude: 79.7036,
    source: 'manual',
  },
  {
    id: 'chengalpattu',
    name: 'Chengalpattu',
    district: 'Chengalpattu',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 12.6819,
    longitude: 79.9888,
    source: 'manual',
  },
  {
    id: 'hosur',
    name: 'Hosur',
    district: 'Krishnagiri',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 12.7409,
    longitude: 77.8253,
    source: 'manual',
  },
  {
    id: 'ooty',
    name: 'Ooty',
    district: 'The Nilgiris',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 11.4102,
    longitude: 76.695,
    source: 'manual',
  },
  {
    id: 'kanyakumari',
    name: 'Kanyakumari',
    district: 'Kanyakumari',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 8.0883,
    longitude: 77.5385,
    source: 'manual',
  },
];
